package com.hunter.javaBase.string;

import com.alibaba.fastjson.JSON;
import com.google.common.collect.Lists;
import org.springframework.util.CollectionUtils;

import java.util.Collections;
import java.util.List;

/**
 * @author hunter.yang
 * @version 1.0
 * @description 文本去重
 * @date 2020/12/15 14:07
 */
public class TextRepairTest {
    
    public static void main(String[] args) {
        String str = "任务：beidian_offline_item_hot_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_item_action_log, beidian_online_items,   beidian_item_show_cart_action_log]\n" +
                "任务：hive2redis_beidian_ads_i2a_bts 上游搜索与推荐组和广告组在线任务：[beidian_ads_i2a_bts,beidian_ads_item_recall,beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log],\n"+
                "任务：beidian_offline_buy_user_trigger_redis 上游搜索与推荐组和广告组在线任务：[beidian_offline_buy_user_trigger,beibei_weixin_beidian_user_item_action_log,beibei_weixin_beidian_device_id_uid_info,beibei_beidian_weixin_ul_id_uid_info,beibei_weixin_beidian_user_item_time_span_action_log_sum,weixin_xiaochengxu_show_click_cart_log,m_zhan_show_click_cart_log,beidian_app_show_click_cart_log,beidian_app_log_day_hour,m_zhan_log_day_hour,weixin_xiaochengxu_log_day_hour,beidian_app_log_day_hour]\n" +
                "任务：beidian_p2i_recom_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n" +
                "任务：beidian_p2i_recom_data_word2vec_redis 上游搜索与推荐组和广告组在线任务：[beidian_online_items,beidian_p2p_recom_action_sim,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n" +
                "任务：beidian_offline_p2i_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n" +
                "任务：hive2redis_beidian_guoyuan_hot_item 上游搜索与推荐组和广告组在线任务：[beidian_guoyuan_hot_item,beidian_online_items,beidian_online_items]\n" +
                "任务：beidian_i2i_recom_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_i2i_recom_data,beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n";


        String strAll = "任务：beidian_offline_item_hot_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_item_action_log, beidian_online_items,   beidian_item_show_cart_action_log]\n" +
        "任务：hive2redis_beidian_ads_i2a_bts 上游搜索与推荐组和广告组在线任务：[beidian_ads_i2a_bts,beidian_ads_item_recall,beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log],\n"+
                "任务：beidian_offline_buy_user_trigger_redis 上游搜索与推荐组和广告组在线任务：[beidian_offline_buy_user_trigger,beibei_weixin_beidian_user_item_action_log,beibei_weixin_beidian_device_id_uid_info,beibei_beidian_weixin_ul_id_uid_info,beibei_weixin_beidian_user_item_time_span_action_log_sum,weixin_xiaochengxu_show_click_cart_log,m_zhan_show_click_cart_log,beidian_app_show_click_cart_log,beidian_app_log_day_hour,m_zhan_log_day_hour,weixin_xiaochengxu_log_day_hour,beidian_app_log_day_hour]\n" +
                "任务：beidian_p2i_recom_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n" +
                "任务：beidian_p2i_recom_data_word2vec_redis 上游搜索与推荐组和广告组在线任务：[beidian_online_items,beidian_p2p_recom_action_sim,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n" +
                "任务：beidian_offline_p2i_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n" +
                "任务：hive2redis_beidian_guoyuan_hot_item 上游搜索与推荐组和广告组在线任务：[beidian_guoyuan_hot_item,beidian_online_items,beidian_online_items]\n" +
                "任务：beidian_i2i_recom_data_redis 上游搜索与推荐组和广告组在线任务：[beidian_i2i_recom_data,beidian_online_items,beidian_p2p_recom_sim,beidian_p2p_recom_action_sim,beidian_p2p_recom_title_word2vec_sim_data_ext,beidian_p2p_show_wbcosine_sim,beidian_p2p_cart_wbcosine_sim,beidian_p2p_buy_wbcosine_sim,beidian_p2p_show_buy_wbcosine_sim,beidian_p2p_show_wbcosine_sim_today,beidian_p2p_show_wbcosine_sim_last_interval,beidian_p2p_show_wbcosine_sim_old_part,beidian_p2p_cart_wbcosine_sim_today,beidian_p2p_cart_wbcosine_sim_last_interval,beidian_p2p_cart_wbcosine_sim_old_part,beidian_p2p_buy_wbcosine_sim_today,beidian_p2p_buy_wbcosine_sim_last_interval,beidian_p2p_buy_wbcosine_sim_old_part,beidian_p2p_show_buy_wbcosine_sim_today,beidian_p2p_show_buy_wbcosine_sim_last_interval,beidian_p2p_show_buy_wbcosine_sim_old_part,beidian_item_action_log,beidian_item_show_cart_action_log,beidian_item_show_cart_action_log]\n";

        String strAll5 =
                "搜索+广告总任务除去以上任务后剩余的在线任务：item_props\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：marttuan_basic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：marttuan_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：marttuan_user_statistics\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_item_action_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_profile\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_keyword_idf\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_keyword_similarity\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：item_props_complement\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_item_action_90day\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_collect_wbcosine_sim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_cart_wbcosine_sim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_buy_wbcosine_sim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：item_profile\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_mix_wbcosine_sim_raw_wilson\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_mix_wbcosine_content_recom_pid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_pid2iid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：offline_user_action\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：offline_u2p\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_items_forward\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：visual_mart_oversea_show\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：event_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_filter_event_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：item_invalid_exposure\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：item_profile_string\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_find_similar_wbcosine_content\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_find_similar_item_recom_pid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_search_action_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：high_frequency_query_word\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_statistic_cvr\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_rerank\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_query_action_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_bidword_demo_query\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：extract_search_keyword\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_queryword_one_dim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_mart_tuan_istop_gmt_show\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：everyday_sales_30d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_report_seller_ad_implement\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_items_typerank\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_online_daybreak\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_ad_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_hive2mysql_rpt_dpf_ad_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：app_decode_recom_log_statistic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query2cat_cat_level_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query2cat_query_item_action_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_ad_keyword_order\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_report_ad\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_report_ad\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query2cat_query2cat_by_click\n";

        String strAll4 =
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_query2cat_query2cat_by_click_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ads_item_recall\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_cat2a_item_add_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_ad_bss_report_seller\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_ad_bss_trade\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_ad_bss_report_ad\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_ad_bss_trade\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query2cat_termweight_query_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_ad_bss_report_ad\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：entry_pic_schedule\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_online_p2i_entry_pic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_entry_pic_schedule\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_entry_pic_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_ad_bss_report_campaign\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_ad_bss_report_campaign\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ads_statistic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：all_scene_report_seller\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_i2i_item_add_ads_bts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2a_item_add_ads_bts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_p2a_item_add_ads_bts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_entry_pic_schedule\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_online_p2i_entry_pic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_entry_pic_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_ad_all_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_hive2mysql_rpt_dpf_ad_all_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_cmpn_ad_rela_info_s_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_app_log_ad_srch_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_cmpn_ad_bidword_s_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_trade_account\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_app_log_recom_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_app_log_ad_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query2cat_query2cat_topleafcat_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_rewrite_query_brand_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_hot_items_by_order_cat2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_item_add_ads_cts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_i2i_item_add_ads_cts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cart_guess_you_like_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_cmpn_ad_campaign_s_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_online_ads_hr\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：get_mslp_ep2p_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_get_mslp_ep2p_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：item_price_level\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_trade_account\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_bss_report_seller_account\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_bss_report_seller_bizresult\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：report_seller_account\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：report_seller_bizresult\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：adcpc_ctr_query_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：seller_post_sale_model\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_seller_post_sale_model\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_seller_post_sale_model\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_cmpn_ad_cpm_cpmn_creative_s_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_bp_cpm_creative_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_bp_cpm_creative_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_bp_all_billing_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：filter_same_picture\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_bp_cpm_creative_filter_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_p2ei_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dws_flow_app_log_ad_cpc_bid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_with_eid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cart_hot_recom_hbase\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_crm_report_seller_cost_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_filter_same_picture\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_filter_same_picture\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_crm_report_seller_cost_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：adcpc_ctr_query_feature_data_table_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_ctr_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_ad_ctr_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_m_log_ad_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_action_180d_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dws_flow_log_ad_cpc_bid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：pur_power_cid_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_cvr_statistic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_ad_cvr_statistic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：marketing_ad_sales_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_query_word_index_bts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：brand_prefer_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cate_prefer_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：brand_type_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cate1_id_prefer_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cate2_id_prefer_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_report_cpc_bidword\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query2cat_random_query_demo_data_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_campaign_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_campaign_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_item_hot_recom_by_cat2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_item_hot_recom_by_cat2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_recom_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_recom_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_crm_spectaculars_private_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_crm_spectaculars_service_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_crm_spectaculars_private_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_crm_spectaculars_service_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_shop_uid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_ad_shop_uid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_bp_report_mall_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cart_ctr_user_feature_raw\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_clusterid_all\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_pid_all\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_hashcode_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_base64_all\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_partsign_lefthash_all\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_imgsim_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_clusterids_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_clustersize_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_ad_mall_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_hive2mysql_rpt_dpf_ad_mall_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：marketing_ad_self_brand_daily_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_self_daily_sendmail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_bp_mall_extend_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_bp_mall_extend_pid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_wxxcx_log_ad_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_wxxcx_log_ad_show_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_view_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_cart_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_favor_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_purchase_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_behavior_agg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_user_behavior_agg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：uid_0_1_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：uid_pre_preg_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_gmv_sales\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_gmv_weight\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：event_main_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ads_item_price\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ads_item_price_hbase\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_report_cps_product\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_report_cps_product\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_items_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：homepage_item_rec_expo_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：homepage_item_rec_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_item_dict_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：offline_user_action_with_platform\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：offline_u2p_with_platform\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_item_dict_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_offline_u2p_with_platform\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：homepage_user_visited_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_visited_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_device_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_log_query\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_demographic_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_ad_query_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：user_common_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_user_common_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_sug_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_search_ad_query_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：leaf_cate_to_cate2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_cate_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_cate_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_item_info_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_only_product\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_category_sales_distribution\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sqoop_rpt_category_sales_distribution\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mainstream_item_pool\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mainstream_product_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mainstream_x2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_mainstream_product_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_mainstream_x2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_mainstream_product_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_online_ads_hr\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mart_item_pool\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_mix_wbcosine_content\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_beidian_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_beidian_hot_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_beidian_item_term_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_beidian_item_term_info\n";

        String strAll2 =
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_item_add_ads_bts_hive\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_online_item_text_partition_word_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_partsign_lefthash_all_channel\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_imgsim_new_channel\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_imgsim_new_total\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_imgsim_textsim_new_total\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_homo_pid_in_review_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_static_relationship\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_ads_item_price\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：app_bargain_recom_item\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bargain_recom_wbcosine_content\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_bargain_recom_p2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_weixin_beidian_user_relation_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_weixin_beidian_user_time_span_relation_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：app_poster_illustration_item\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bargain_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_action_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_active_user\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_homo_pid_in_review_marttuan_item_candidate_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_hashcode_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_base64_all\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_partsign_lefthash_all\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_partsign_lefthash_all_channel\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_imgsim_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_imgsim_new_channel\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_rect_img_imgsim_new_total\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：imgsim_marttuan_homo_iid_sim_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_type_and_nearestuid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_user_type_and_nearestuid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_user_type_and_nearestuid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_pid_actioned_count_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_actioned_data_with_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cart_example_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cart_example_data_final\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cart_wdl_fg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_for_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_beidian_cart_product_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_cart_user_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_item_pool\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_x2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_product_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bd_mainstream_x2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_generate_mainstream_product_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_bd_mainstream_product_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mainstream_item_feature_for_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mainstream_item_feature_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_mainstream_item_feature_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：leaf_cate_to_cate1\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_cate_dict1\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_cate_dict1\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_beidian_brand_alias\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_view_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_cart_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cart_example_data_final_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cart_wdl_fg_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：xinde_term_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：xinde_content_simlarity\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_week_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_homepage_expo_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_homepage_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cart_user_history_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_cart_user_history_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_community_item\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_community_term_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_community_content_simlarity\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_community_action_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_trade_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_seller_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cate_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cate1_ipv\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_cart\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_cart\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_seller_cart\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cate_cart\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cate1_cart\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cate_avg_price\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_expo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cate_expo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_seller_expo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_expo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_brand_index_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_item_v2_index_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_ipv_rank\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_item_index_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_pay_rank\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_mall_index_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_seller_comment\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_brand_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_item_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_item_v2_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_mall_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_do_has_cost_seller_1m\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_syn_campaign_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_clear_cpc_campaign_creating\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_brand_material_error\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_redpack_expire\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_syn_mall_extend\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_syn_account_balance\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_syn_account_redpack_balance\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_seller_msg_balance\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_campaign_mall_promotion\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_campaign_intel_promotion\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbyxt_seller_advert_pay\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_community_action_log_60day\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_xinde_show_wbcosine_sim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_repository_id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_query_action_log_di\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_convertion_info_dd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_index_dd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_word_index_bb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_word_index_paldb_bb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_query_term_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_homepage_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_raw_sample_select\n" +
                "搜索+广告总任务除去以上任务后剩余的在线告总任务除去以上任务后剩余的在线任务：bd_mainstream_sample_to_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_bdapp_log_ad_srch_show_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_bdapp_log_ad_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_ad_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_ad_bidword_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_bidword_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_bidword_infos\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_beidian_index_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_bdapp_log_ad_srch_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_active_user\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_cpc_bidword_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_seller_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_seller_info_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_cpc_avg_data_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_community_initial_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_fin_bdapp_seller_ad_pay_log_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_cmpn_bdapp_ad_bidword_s_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_homepage_performance_report\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_community_i2i_sim_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_seller_info_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_bd_community_info_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_cpc_bidword_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_label_index_reverse_paldb_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_seller_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_cpc_avg_data_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bd_community_info_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_beidian_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_cmpn_bidword_infos_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_cmpn_bidword_infos_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_qr_query_cat_more\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dws_flow_bdapp_log_ad_cpc_bid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_product_cms\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cart_hot_recom_hbase_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_item_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：test.sh\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_sample_with_user_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bdyxt_seller_advert_pay\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_ctr_original_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_ad_ctr_example_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_query_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_char_index_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dumps_query_category_classification_query_char_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_product_features\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_product_feature_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_bd_mainstream_product_feature_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_scene_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_aibot_index_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_scene_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_aibot_index_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dumps_category_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_cmpn_bdapp_cmpn_stmt_info_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_cpc_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_rpt_dpf_bd_ad_cpc_kpi_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_search_beidian_query_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_search_beidian_query_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_fensi_relation_strength_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_fensi_active_degree_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_trde_bd_ord_ad_lead_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_bss_slr_cmpn_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_bss_slr_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ads_p2a\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_fensi_relation_recom_offline_trigger\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_fensi_relation_recom_offline_trigger_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_hot_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_online_ads_hr\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_online_ads_hr\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_hot_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ads_p2a\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_bss_slr_brd_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_uid_map_shopid_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_uid_map_shopid_data_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_is_fans\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_user_is_fans\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_bdapp_log_recom_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_bdapp_log_ad_show_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bb_community_item\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_xinde_recom_info_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hbase_xinde_recom_info_v2_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_shop_visitor_history_statistics\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_dianzhu_shop_visitor_history_statistics_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_label_index_reverse_paldb_bb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_shop_history_logs\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_shop_history_logs\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_shop_history_logs\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_fans_is_valueable_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_category_info_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_category_info_bb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_label_index_bb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_label_index_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_word_index_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_fans_is_valueable_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_word_index_paldb_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_category_weight_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：query_category_classification_train_eval_weight_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_hot_sale\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_hot_sale_catory_redis_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_tree_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_m_bd_ad_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：brand_hot_sale\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_hot_sale_brand_redis_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dws_flow_m_bd_ad_cpc_bid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dws_flow_log_bd_ad_cpc_bid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_gift_packag_item_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_gift_packag_item_data_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_m_bd_ad_show_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_short_title\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_item_short_title\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_samples\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_crm_slr_cost_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：title_category_info_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：title_word_index_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：title_label_index_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：pid_action_count_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：pid_crt_pay_count_xl\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_query_cid_2_c2id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_query_cid_2_c2id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_brand_query\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbalog_bd_log_solution_rate_h\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_bd_ab_rate_report_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_homepage_share_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_cid_2_c1id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_cid_2_c1id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_p2q_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_q2p_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_shop_visit_stat\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_simrank\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_favor_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_qQ_NQ\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_share_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_cate_share_prefer\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_cate1_share_prefer\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_brand_share_prefer\n";

        String strAll3 =
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_guoyuan_hot_item\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_ad_daily\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_ads_hr_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_m_bd_log_srch_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_simrank_rst\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dumps_brand_category_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：brand_category\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_query_rewrite_simrank_base_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bidword_demo_query\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_query_word_index_bts\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_queryword_one_dim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_extend\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_i2i_item_recom_pid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_ad_bidword_extend\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_bidword_extend\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：cate_interevene\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dumps_cate_intervene\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_wdl_fg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dressup_item_pool\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dressup_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_dressup_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_dressup_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_item_pool\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_tab_x2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bd_tab_x2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_tab_i2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bd_tab_i2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_item_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：generate_bd_item_info_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_bd_item_info_dict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：title_word_index_paldb_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：title_label_index_reverse_palbd_bd\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_ctr_example\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_purchase_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_user_behavior_agg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_bd_user_behavior_agg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_guoyuan_special_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_guoyuan_special_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_guoyuan_special_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_new_for_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_new_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_beidian_item_feature_new_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_ctr_wdl_fg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_special_items\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_special_items_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beibei_special_items_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_ad_bidword_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_update\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_ad_bidword_update\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_online_ads_hr_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_common\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_behavior_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_seller_behavior_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_target_user_num\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_feature_common_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：paldb_beidian_item_feature_common\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_beidian_item_feature_common\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beibei_app_log_search_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_ad_target_user_num\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_target_user_num\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_pids_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_pids_info_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_online_pids_info_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_pid2adid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_pid2adid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_user_seller_behavior_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_user_seller_behavior_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_smart_bidword_candidate_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：community_post_type\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_beidian_community_video\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_community_video\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_beidian_community_video_trigger\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_target_similar_shop\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_target_similar_shop_user_num\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_cate3_prefer\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_target_cate_prefer_user_num\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_ad_target_similar_shop\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_target_similar_shop\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_beidian_brand_user_price_manual_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_user_price_manual_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_audience_bidding_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_cate_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_cate_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_guess_you_like_click\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：i2i_guess_you_like_show\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bb_refund_imgs_update\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_cvr_example\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_cvr_example_with_behaviors\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_guess_you_like_train\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_guess_you_like_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_beidian_brand_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_log_query_weight\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_cate_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_cate_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_mart_item_new_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_mart_item_new_prod\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_mart_item_new_incre_prod\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beidian_log_query_day\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_guess_you_like_xgboost_train\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_guess_you_like_fg\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：shell_p2p_guess_you_like_xgboost_train\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_xgboost_predict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：shell_p2p_predict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_esmm_fg_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：p2p_xgboost_output\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_item_rmk_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_origin_s_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_rpt_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_rpt_cm_m\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_beidian_brand_rpt_cm_m\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_terms\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_product_online_terms\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：delete_unuse_hive\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_esmm_fg_tfrecord_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：delete_unuse_hbase\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_beidian_search_ad_esmm_din_model\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_origin_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_example\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_example_with_behaviors\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_example_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_dpf_bd_ad_scene_kpi_1d_d_ab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ads_activity_item_recall\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_ads_p2a\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_hot_activity_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_hot_activity_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_activity_ads_p2a\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_activity_ad_cate_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：delete_online_item_hbase\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_ad_cvr_statistic\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ads_activity_item_tab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ads_activity_item_tab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：test_syn_dws_mix_dmn_v2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bb_select_jd_url\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mainstream_item_pool_normal\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：redis_mainstream_item_pool_noraml\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：mail_over_budget_campaign\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：rpt_beidian_over_budget_campaign\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hve2redis_query_rewrite_query_brand_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_query2cat_random_query_demo_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_query2cat_query2cat_by_click_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_adcpc_ctr_query_feature_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_scene_group_map\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_ad_scene_group_map\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_ad_crowd_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_ad_unit_recom_scene_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bdapp_log_ad_show_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：m_bd_ad_show_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_bd_ad_unit_recom_scene_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cate_tab_mapping\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_tab_order_cnt\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_tab_prefer\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_hot_tab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_user_tab_prefer\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_hot_tab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_ad_item_map\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_ad_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_brand_ad_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_brand_ad_hot\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_ad_p2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2reids_beidian_brand_ad_p2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_brand_ad_iid_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_brand_ad_fullIndex\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_ord_ad_lead_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_good_shopkeeper_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_good_shopkeeper_num_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_good_shopkeeper_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beicang_brand_query\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_wxxcx_bd_log_recom_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：yxt_bd_ad_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_wxxcx_bd_log_ad_clk_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：yxt_bd_seller_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dwb_flow_wxxcx_bd_log_ad_show_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dws_flow_wxxcx_bd_ad_cpc_bid_1d_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_prod_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：yxt_bd_prod_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_ad_cloud_overbid_suggest_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_shopkeeper_prod_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_cateprefer_prod_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_similaritem_prod_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_shop_prod_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_similarshop_prod_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_seller_true_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_cloud_cate3_true_act\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：yxt_bd_cate3_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_ad_show_log_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_ad_click_log_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_ad_order_lead_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_ad_campaign_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_brand_ad_cost_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_bd_brand_ad_cost_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_bd_brand_ad_cost_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_bd_brand_ad_campaign_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_bd_brand_ad_campaign_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_ctr_example_with_behaviors\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_ctr_fg_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_bd_ad_cloud_overbid_suggest_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_bd_ad_cloud_overbid_suggest_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_ads_p2a_tab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_activity_ads_p2a_tab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_bigsale_pay_crowd_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_query2cids\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_2_cids\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_brand_2_cids\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_example_for_bst\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_example_for_bst_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_bd_readtime_repository_id_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_aibot_bd_realtime_repository_id_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_video_ad_index_pre\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ad_video_ad_index\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_video_ad_items_recall\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_video_ad_p2a\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_video_hot_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_video_hot_ads\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_video_ad_p2a\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_video_iid2adid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_video_ad_show_log_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_video_ad_order_lead_i_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_video_ad_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_video_ad_seller_cost_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_bd_video_ad_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2mysql_bd_video_ad_seller_cost_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_high_pay_crowd_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_cvr_example\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_beidai_repository_id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_aibot_beidai_index_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_aibot_beidai_index_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_cvr_example_with_behavior\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_cvr_example_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_bidword_recall_word2vec_prepare\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_item_info_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_item_info_paldb_transform\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：dump_bd_item_info_paldb\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_bc_realtime_repository_id_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bc_eventid_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_bc_eventid_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_bc_realtime_hive2redis_repository_id_2_question_detail\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_bc_today\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bc_new_eventid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_bc_realtime_id_repositoryid_map\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：aibot_bc_realtime_hive2redis_id_repositoryid_map\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_video_ad_scene_rpt_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_sug_index_bar\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_ad_cvr_esmm_tfrecord2_captain\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：temp_shell\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_sample_with_item_feature_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_mainstream_sample_with_user_feature_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_beidian_mainstream_item_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_beidian_mainstream_user_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_materials_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive_beidian_materials_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_materials_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_share_imgs_update\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beicang_log_query_weight\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beicang_sug_index_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：spark-on-k8s-job-clean-crontab\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_beicang_log_query_day\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：ml_BI_case_predict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_sample_with_behaviors\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_feature_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_sample_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_items_info_4filter\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：online_items_info_4filter_hive2redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_ctr_din_sample_with_behaviors\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_ctr_din_feature\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_ctr_din_feature_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_ctr_din_sample\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_sample_with_behaviors_v3\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_feature_v3\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_money_ctr_din_feature_tfrecord_v3\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_visit_brands_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_user_visit_brands_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_offline_hot_brands\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_offline_hot_brands\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_p2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_brand_p2i\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_brand_i2trend\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：hive2redis_beidian_brand_i2trend\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bd_search_gy_iid\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_recom_log_info_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_homepage_list_show_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_recom_user_feature_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_homepage_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_homepage_tab_list_show_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_homepage_tab_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_product_detail_recom_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidia_search_recom_item_feature_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_shopping_link_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_hive_category_prod\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_recom_log_info_sample_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_recom_user_click_behavior_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_scene_show_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_scene_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_scene_show_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_scene_orchard_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_recom_cvr_din_feature_1d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_es_product_click_info\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_search_recom_cvr_din_feature_1d_tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_i2i_title_recom_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_p2p_title_recom_sim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_shopping_link_show_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_product_detail_recom_show_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_mart_item_pre_new_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_goods_big_package_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_goods_recomm_show_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_goods_tuan_oversea_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_goods_tuan_single_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_oversea_mall_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_oversea_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_oversea_show_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_show_oversea_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：coreseek_show_prod_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_gmv_sales_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_algorithm_seg_pre_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_algorithm_seg_prod_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：product_algorithm_seg_incre_prod_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_rank_basic_features_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_mart_item_prod_new_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：brand_sale_hive2es_offline_cluster\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：search_mart_item_prod_incre_new_offline\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：app_bbalog_bdian_ad_video_bid_rec_df\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：datax_hive2mysql_app_bbalog_bdian_ad_video_bid_rec_df\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cid_hot_sale_id_hive2redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_trde_order_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_scene_orchard_show_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_activity_scene_orchard_show_click_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_cid_hot_sale_id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_items_feature_4_predict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_items_feature_4_predict_hive2tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_ads_feature_4_predict\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_ads_feature_4_predict_hive2tfrecord\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_rank_list_id\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_online_rank_list_id_hive2redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_user_feature_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_ad_recom_u2i_example_tfrecord_shuffle\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_position_indicator_click\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_position_indicator_show\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：novelty_indicator_click\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_shopping_link_show_log\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：novelty_indicator_show\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：category_click_statistics\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：flink_realtime_behaviors\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：flink_realtime_session_order2redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_collocation_recom_sim\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_main_recom\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_main_recom_hive2redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_collocation_recom_demo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_collocation_recom_data_demo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_collocation_recom_hive2redis_demo\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_diversity_novelty_report_d\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：bbalog_bd_ab_report_rate_statistic_d_new\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_collocation_recom_data\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：beidian_collocation_recom_data_redis\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_all_brand_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_all_category_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_brand_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_category_task2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_category_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_hot_sale_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_hot_search_task_4\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_hot_search_task_2\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_hot_search_task_5\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_prop_search_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_hot_search_task\n" +
                "搜索+广告总任务除去以上任务后剩余的在线任务：sync_hot_search_task_3";
        StringBuilder target = new StringBuilder();

        strAll = strAll.replaceAll("：", "：,");
        strAll2 = strAll2.replaceAll("：", "：,");
        strAll3 = strAll3.replaceAll("：", "：,");
        strAll4 = strAll4.replaceAll("：", "：,");
        strAll5 = strAll5.replaceAll("：", "：,");

        String[] strList = strAll.split(",");
        for (String strFor : strList) {
            if (target.toString().contains(strFor)) {
                continue;
            }
            target.append(strFor).append(",");
        }

        String[] str2List = strAll2.split(",");
        for (String strFor : str2List) {
            if (target.toString().contains(strFor)) {
                continue;
            }
            target.append(strFor).append(",");
        }

        String[] str3List = strAll3.split(",");
        for (String strFor : str3List) {
            if (target.toString().contains(strFor)) {
                continue;
            }
            target.append(strFor).append(",");
        }

        String[] str4List = strAll4.split(",");
        for (String strFor : str4List) {
            if (target.toString().contains(strFor)) {
                continue;
            }
            target.append(strFor).append(",");
        }

        String[] str5List = strAll5.split(",");
        for (String strFor : str5List) {
            if (target.toString().contains(strFor)) {
                continue;
            }
            target.append(strFor).append(",");
        }

        System.out.println(target);
    }
}
