package com.hunter.BizTest;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;
import org.apache.commons.lang3.StringUtils;

import java.util.List;

/**
 * @description:
 * @author: hunter.yang
 * @date: 20201228 16:01
 */
public class MaterialTest {

    public static void main(String[] args) {

        String conf = "[{\n" +
                "\t\"categoryName\": \"精选\",\n" +
                "\t\"categoryId\": 1,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 100,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15942369,\n" +
                "\t\t\t\"articleId\": 209,\n" +
                "\t\t\t\"sortId\": 27\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15811465,\n" +
                "\t\t\t\"articleId\": 187,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17976932,\n" +
                "\t\t\t\"articleId\": 215,\n" +
                "\t\t\t\"sortId\": 18\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17206102,\n" +
                "\t\t\t\"sortId\": 12\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17814507,\n" +
                "\t\t\t\"sortId\": 22\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17864303,\n" +
                "\t\t\t\"articleId\": 210,\n" +
                "\t\t\t\"sortId\": 14\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13820444,\n" +
                "\t\t\t\"articleId\": 214,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14445231,\n" +
                "\t\t\t\"articleId\": 196,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12796981,\n" +
                "\t\t\t\"articleId\": 193,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14202562,\n" +
                "\t\t\t\"articleId\": 198,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15465964,\n" +
                "\t\t\t\"articleId\": 233,\n" +
                "\t\t\t\"sortId\": 23\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16729614,\n" +
                "\t\t\t\"articleId\": 246,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16583066,\n" +
                "\t\t\t\"articleId\": 234,\n" +
                "\t\t\t\"sortId\": 15\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15089120,\n" +
                "\t\t\t\"articleId\": 204,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17990592,\n" +
                "\t\t\t\"articleId\": 148,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12837259,\n" +
                "\t\t\t\"sortId\": 24\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12485447,\n" +
                "\t\t\t\"articleId\": 252,\n" +
                "\t\t\t\"sortId\": 19\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17062364,\n" +
                "\t\t\t\"articleId\": 195,\n" +
                "\t\t\t\"sortId\": 13\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14464227,\n" +
                "\t\t\t\"articleId\": 236,\n" +
                "\t\t\t\"sortId\": 25\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16734856,\n" +
                "\t\t\t\"articleId\": 247,\n" +
                "\t\t\t\"sortId\": 16\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16756480,\n" +
                "\t\t\t\"articleId\": 235,\n" +
                "\t\t\t\"sortId\": 29\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16148520,\n" +
                "\t\t\t\"articleId\": 205,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16188742,\n" +
                "\t\t\t\"articleId\": 149,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16478845,\n" +
                "\t\t\t\"articleId\": 231,\n" +
                "\t\t\t\"sortId\": 17\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17157950,\n" +
                "\t\t\t\"articleId\": 206,\n" +
                "\t\t\t\"sortId\": 20\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14259699,\n" +
                "\t\t\t\"articleId\": 207,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15393263,\n" +
                "\t\t\t\"articleId\": 202,\n" +
                "\t\t\t\"sortId\": 21\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13631602,\n" +
                "\t\t\t\"articleId\": 238,\n" +
                "\t\t\t\"sortId\": 26\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17966873,\n" +
                "\t\t\t\"articleId\": 239,\n" +
                "\t\t\t\"sortId\": 28\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15891910,\n" +
                "\t\t\t\"articleId\": 251,\n" +
                "\t\t\t\"sortId\": 30\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16438750,\n" +
                "\t\t\t\"articleId\": 241,\n" +
                "\t\t\t\"sortId\": 31\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17063081,\n" +
                "\t\t\t\"articleId\": 242,\n" +
                "\t\t\t\"sortId\": 32\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"母婴\",\n" +
                "\t\"categoryId\": 2,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 700,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15942369,\n" +
                "\t\t\t\"articleId\": 209,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15811465,\n" +
                "\t\t\t\"articleId\": 187,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17976932,\n" +
                "\t\t\t\"articleId\": 215,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14075830,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17413629,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17866902,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13047197,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17976980,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17206102,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17814507,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17859368,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17803178,\n" +
                "\t\t\t\"sortId\": 12\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17864303,\n" +
                "\t\t\t\"articleId\": 210,\n" +
                "\t\t\t\"sortId\": 13\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13820444,\n" +
                "\t\t\t\"articleId\": 214,\n" +
                "\t\t\t\"sortId\": 14\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16915513,\n" +
                "\t\t\t\"sortId\": 15\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 18018274,\n" +
                "\t\t\t\"sortId\": 16\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16696377,\n" +
                "\t\t\t\"sortId\": 17\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17237693,\n" +
                "\t\t\t\"sortId\": 18\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17861483,\n" +
                "\t\t\t\"sortId\": 19\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17861483,\n" +
                "\t\t\t\"sortId\": 20\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16931817,\n" +
                "\t\t\t\"sortId\": 21\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"categoryIdSecName\": \"奶纸\",\n" +
                "\t\t\"categoryIdSec\": 701,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15942369,\n" +
                "\t\t\t\"articleId\": 209,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15811465,\n" +
                "\t\t\t\"articleId\": 187,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17976932,\n" +
                "\t\t\t\"articleId\": 215,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14075830,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17413629,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17866902,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13047197,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17976980,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"categoryIdSecName\": \"婴童用品\",\n" +
                "\t\t\"categoryIdSec\": 702,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17206102,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17814507,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17859368,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17803178,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"categoryIdSecName\": \"玩具\",\n" +
                "\t\t\"categoryIdSec\": 703,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17864303,\n" +
                "\t\t\t\"articleId\": 210,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13820444,\n" +
                "\t\t\t\"articleId\": 214,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16915513,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 18018274,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16696377,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17237693,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17861483,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17861483,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16931817,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"居家\",\n" +
                "\t\"categoryId\": 3,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 300,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14445231,\n" +
                "\t\t\t\"articleId\": 196,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12796981,\n" +
                "\t\t\t\"articleId\": 193,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14202562,\n" +
                "\t\t\t\"articleId\": 198,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14126764,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15838762,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15465964,\n" +
                "\t\t\t\"articleId\": 233,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16729614,\n" +
                "\t\t\t\"articleId\": 246,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17987124,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16583066,\n" +
                "\t\t\t\"articleId\": 234,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15089120,\n" +
                "\t\t\t\"articleId\": 204,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17990592,\n" +
                "\t\t\t\"articleId\": 148,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12837259,\n" +
                "\t\t\t\"sortId\": 12\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13621510,\n" +
                "\t\t\t\"sortId\": 13\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12485447,\n" +
                "\t\t\t\"articleId\": 252,\n" +
                "\t\t\t\"sortId\": 14\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17085175,\n" +
                "\t\t\t\"sortId\": 15\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16673622,\n" +
                "\t\t\t\"sortId\": 16\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17062364,\n" +
                "\t\t\t\"sortId\": 17\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14464227,\n" +
                "\t\t\t\"articleId\": 236,\n" +
                "\t\t\t\"sortId\": 18\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16734856,\n" +
                "\t\t\t\"articleId\": 247,\n" +
                "\t\t\t\"sortId\": 19\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16756480,\n" +
                "\t\t\t\"articleId\": 235,\n" +
                "\t\t\t\"sortId\": 20\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"categoryIdSecName\": \"生活家电\",\n" +
                "\t\t\"categoryIdSec\": 801,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14445231,\n" +
                "\t\t\t\"articleId\": 196,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12796981,\n" +
                "\t\t\t\"articleId\": 193,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14202562,\n" +
                "\t\t\t\"articleId\": 198,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14126764,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15838762,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15465964,\n" +
                "\t\t\t\"articleId\": 233,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16729614,\n" +
                "\t\t\t\"articleId\": 246,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17987124,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16583066,\n" +
                "\t\t\t\"articleId\": 234,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"categoryIdSecName\": \"居家百货\",\n" +
                "\t\t\"categoryIdSec\": 802,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15089120,\n" +
                "\t\t\t\"articleId\": 204,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17990592,\n" +
                "\t\t\t\"articleId\": 148,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12837259,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13621510,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 12485447,\n" +
                "\t\t\t\"articleId\": 252,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17085175,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16673622,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17062364,\n" +
                "\t\t\t\"articleId\": 195,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14464227,\n" +
                "\t\t\t\"articleId\": 236,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16734856,\n" +
                "\t\t\t\"articleId\": 247,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16756480,\n" +
                "\t\t\t\"articleId\": 235,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"categoryIdSecName\": \"家纺\",\n" +
                "\t\t\"categoryIdSec\": 803,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 20626,\n" +
                "\t\t\t\"uid\": 130021082,\n" +
                "\t\t\t\"articleId\": 217,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 41964,\n" +
                "\t\t\t\"uid\": 127877400,\n" +
                "\t\t\t\"articleId\": 143,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 50047,\n" +
                "\t\t\t\"uid\": 129304791,\n" +
                "\t\t\t\"articleId\": 219,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 20517,\n" +
                "\t\t\t\"uid\": 128285319,\n" +
                "\t\t\t\"articleId\": 191,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 48529,\n" +
                "\t\t\t\"uid\": 125441699,\n" +
                "\t\t\t\"articleId\": 218,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 100356,\n" +
                "\t\t\t\"uid\": 136069099,\n" +
                "\t\t\t\"articleId\": 154,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 48822,\n" +
                "\t\t\t\"uid\": 137874307,\n" +
                "\t\t\t\"articleId\": 237,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 42957,\n" +
                "\t\t\t\"uid\": 126689210,\n" +
                "\t\t\t\"articleId\": 240,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"美妆\",\n" +
                "\t\"categoryId\": 4,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 400,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16148520,\n" +
                "\t\t\t\"articleId\": 205,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16188742,\n" +
                "\t\t\t\"articleId\": 149,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16478845,\n" +
                "\t\t\t\"articleId\": 231,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17157950,\n" +
                "\t\t\t\"articleId\": 206,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 14259699,\n" +
                "\t\t\t\"articleId\": 207,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15393263,\n" +
                "\t\t\t\"articleId\": 202,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13979615,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15836002,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16435982,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16435471,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13583258,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 13631602,\n" +
                "\t\t\t\"articleId\": 238,\n" +
                "\t\t\t\"sortId\": 12\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16435652,\n" +
                "\t\t\t\"sortId\": 13\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17966873,\n" +
                "\t\t\t\"sortId\": 14\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15891910,\n" +
                "\t\t\t\"articleId\": 251,\n" +
                "\t\t\t\"sortId\": 16\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16201174,\n" +
                "\t\t\t\"sortId\": 17\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 16438750,\n" +
                "\t\t\t\"articleId\": 241,\n" +
                "\t\t\t\"sortId\": 18\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 17063081,\n" +
                "\t\t\t\"articleId\": 242,\n" +
                "\t\t\t\"sortId\": 19\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 1,\n" +
                "\t\t\t\"pid\": 15475837,\n" +
                "\t\t\t\"sortId\": 20\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"女装\",\n" +
                "\t\"categoryId\": 5,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 500,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99691,\n" +
                "\t\t\t\"uid\": 126868629,\n" +
                "\t\t\t\"articleId\": 211,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 9635,\n" +
                "\t\t\t\"uid\": 89862091,\n" +
                "\t\t\t\"articleId\": 139,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 100625,\n" +
                "\t\t\t\"uid\": 138709817,\n" +
                "\t\t\t\"articleId\": 213,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 8699,\n" +
                "\t\t\t\"uid\": 134404602,\n" +
                "\t\t\t\"articleId\": 212,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 49471,\n" +
                "\t\t\t\"uid\": 130426622,\n" +
                "\t\t\t\"articleId\": 164,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 52321,\n" +
                "\t\t\t\"uid\": 128403383,\n" +
                "\t\t\t\"articleId\": 147,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 28273,\n" +
                "\t\t\t\"uid\": 1129718564,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99690,\n" +
                "\t\t\t\"uid\": 126868629,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 25201,\n" +
                "\t\t\t\"uid\": 139474124,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 50014,\n" +
                "\t\t\t\"uid\": 127717395,\n" +
                "\t\t\t\"articleId\": 253,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 17158,\n" +
                "\t\t\t\"uid\": 128396440,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 8304,\n" +
                "\t\t\t\"uid\": 125683290,\n" +
                "\t\t\t\"articleId\": 230,\n" +
                "\t\t\t\"sortId\": 12\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 13883,\n" +
                "\t\t\t\"uid\": 125843918,\n" +
                "\t\t\t\"articleId\": 229,\n" +
                "\t\t\t\"sortId\": 13\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 20386,\n" +
                "\t\t\t\"uid\": 133678202,\n" +
                "\t\t\t\"articleId\": 254,\n" +
                "\t\t\t\"sortId\": 14\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 8314,\n" +
                "\t\t\t\"uid\": 138904921,\n" +
                "\t\t\t\"sortId\": 15\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 46166,\n" +
                "\t\t\t\"uid\": 125433103,\n" +
                "\t\t\t\"articleId\": 244,\n" +
                "\t\t\t\"sortId\": 16\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"男装\",\n" +
                "\t\"categoryId\": 6,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 600,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 25201,\n" +
                "\t\t\t\"uid\": 128762412,\n" +
                "\t\t\t\"articleId\": 183,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 100359,\n" +
                "\t\t\t\"uid\": 125888722,\n" +
                "\t\t\t\"articleId\": 189,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 28128,\n" +
                "\t\t\t\"uid\": 128912781,\n" +
                "\t\t\t\"articleId\": 181,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 27802,\n" +
                "\t\t\t\"uid\": 129572777,\n" +
                "\t\t\t\"articleId\": 173,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 28273,\n" +
                "\t\t\t\"uid\": 130179377,\n" +
                "\t\t\t\"articleId\": 172,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99103,\n" +
                "\t\t\t\"uid\": 132190765,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 11551,\n" +
                "\t\t\t\"uid\": 126914307,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 52585,\n" +
                "\t\t\t\"uid\": 126846959,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 100499,\n" +
                "\t\t\t\"uid\": 138670289,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 3624,\n" +
                "\t\t\t\"uid\": 127730621,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 47047,\n" +
                "\t\t\t\"uid\": 127353743,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"童装\",\n" +
                "\t\"categoryId\": 7,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 700,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 37,\n" +
                "\t\t\t\"uid\": 126199027,\n" +
                "\t\t\t\"articleId\": 138,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 49496,\n" +
                "\t\t\t\"uid\": 128401671,\n" +
                "\t\t\t\"articleId\": 160,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 7162,\n" +
                "\t\t\t\"uid\": 126199668,\n" +
                "\t\t\t\"articleId\": 161,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99047,\n" +
                "\t\t\t\"uid\": 138119932,\n" +
                "\t\t\t\"articleId\": 165,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 43,\n" +
                "\t\t\t\"uid\": 135234472,\n" +
                "\t\t\t\"articleId\": 184,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 7291,\n" +
                "\t\t\t\"uid\": 126148140,\n" +
                "\t\t\t\"articleId\": 186,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 1547,\n" +
                "\t\t\t\"uid\": 125377680,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99047,\n" +
                "\t\t\t\"uid\": 138119932,\n" +
                "\t\t\t\"articleId\": 165,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 40,\n" +
                "\t\t\t\"uid\": 139245659,\n" +
                "\t\t\t\"articleId\": 227,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 43,\n" +
                "\t\t\t\"uid\": 135234472,\n" +
                "\t\t\t\"articleId\": 184,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 7291,\n" +
                "\t\t\t\"uid\": 126148140,\n" +
                "\t\t\t\"articleId\": 186,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 42,\n" +
                "\t\t\t\"uid\": 137743791,\n" +
                "\t\t\t\"articleId\": 190,\n" +
                "\t\t\t\"sortId\": 12\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 52854,\n" +
                "\t\t\t\"uid\": 135339825,\n" +
                "\t\t\t\"articleId\": 228,\n" +
                "\t\t\t\"sortId\": 13\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 1547,\n" +
                "\t\t\t\"uid\": 125377680,\n" +
                "\t\t\t\"sortId\": 14\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 40,\n" +
                "\t\t\t\"uid\": 139245659,\n" +
                "\t\t\t\"articleId\": 227,\n" +
                "\t\t\t\"sortId\": 15\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 7196,\n" +
                "\t\t\t\"uid\": 128886111,\n" +
                "\t\t\t\"sortId\": 16\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99759,\n" +
                "\t\t\t\"uid\": 139104755,\n" +
                "\t\t\t\"articleId\": 232,\n" +
                "\t\t\t\"sortId\": 17\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 1000,\n" +
                "\t\t\t\"uid\": 135190076,\n" +
                "\t\t\t\"sortId\": 18\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 2469,\n" +
                "\t\t\t\"uid\": 126466216,\n" +
                "\t\t\t\"sortId\": 19\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 110,\n" +
                "\t\t\t\"uid\": 135260015,\n" +
                "\t\t\t\"sortId\": 20\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"鞋靴\",\n" +
                "\t\"categoryId\": 8,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 800,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 42316,\n" +
                "\t\t\t\"uid\": 125363025,\n" +
                "\t\t\t\"articleId\": 199,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 19653,\n" +
                "\t\t\t\"uid\": 135554639,\n" +
                "\t\t\t\"articleId\": 145,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 1691,\n" +
                "\t\t\t\"uid\": 127525300,\n" +
                "\t\t\t\"articleId\": 188,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 8631,\n" +
                "\t\t\t\"uid\": 125458024,\n" +
                "\t\t\t\"articleId\": 192,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 99675,\n" +
                "\t\t\t\"uid\": 137488758,\n" +
                "\t\t\t\"articleId\": 157,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 102,\n" +
                "\t\t\t\"uid\": 133241101,\n" +
                "\t\t\t\"articleId\": 226,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 48718,\n" +
                "\t\t\t\"uid\": 126202766,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 10183,\n" +
                "\t\t\t\"uid\": 126158412,\n" +
                "\t\t\t\"articleId\": 243,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"运动\",\n" +
                "\t\"categoryId\": 9,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 900,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 50038,\n" +
                "\t\t\t\"uid\": 129504793,\n" +
                "\t\t\t\"articleId\": 166,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 4701,\n" +
                "\t\t\t\"uid\": 130778196,\n" +
                "\t\t\t\"articleId\": 222,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 2844,\n" +
                "\t\t\t\"uid\": 138629544,\n" +
                "\t\t\t\"articleId\": 197,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 50939,\n" +
                "\t\t\t\"uid\": 131422713,\n" +
                "\t\t\t\"articleId\": 194,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 43103,\n" +
                "\t\t\t\"uid\": 130748377,\n" +
                "\t\t\t\"articleId\": 223,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"包配\",\n" +
                "\t\"categoryId\": 10,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 1000,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 50762,\n" +
                "\t\t\t\"uid\": 131018857,\n" +
                "\t\t\t\"articleId\": 151,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 20110,\n" +
                "\t\t\t\"uid\": 132251315,\n" +
                "\t\t\t\"articleId\": 200,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 20108,\n" +
                "\t\t\t\"uid\": 131018857,\n" +
                "\t\t\t\"articleId\": 144,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 100158,\n" +
                "\t\t\t\"uid\": 137789342,\n" +
                "\t\t\t\"articleId\": 216,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 50805,\n" +
                "\t\t\t\"uid\": 131154591,\n" +
                "\t\t\t\"articleId\": 225,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 7165,\n" +
                "\t\t\t\"uid\": 131359664,\n" +
                "\t\t\t\"articleId\": 220,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 12436,\n" +
                "\t\t\t\"uid\": 125366451,\n" +
                "\t\t\t\"articleId\": 248,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 20470,\n" +
                "\t\t\t\"uid\": 134182044,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 101018,\n" +
                "\t\t\t\"uid\": 131262453,\n" +
                "\t\t\t\"sortId\": 9\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 52382,\n" +
                "\t\t\t\"uid\": 131393025,\n" +
                "\t\t\t\"sortId\": 10\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 23969,\n" +
                "\t\t\t\"uid\": 129958563,\n" +
                "\t\t\t\"sortId\": 11\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}, {\n" +
                "\t\"categoryName\": \"内衣\",\n" +
                "\t\"categoryId\": 11,\n" +
                "\t\"subCategories\": [{\n" +
                "\t\t\"categoryIdSecName\": \"全部\",\n" +
                "\t\t\"categoryIdSec\": 1100,\n" +
                "\t\t\"pidOrBrandLinkArticles\": [{\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 13205,\n" +
                "\t\t\t\"uid\": 137795157,\n" +
                "\t\t\t\"articleId\": 201,\n" +
                "\t\t\t\"sortId\": 1\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 7283,\n" +
                "\t\t\t\"uid\": 127588226,\n" +
                "\t\t\t\"articleId\": 221,\n" +
                "\t\t\t\"sortId\": 2\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 12091,\n" +
                "\t\t\t\"uid\": 126658955,\n" +
                "\t\t\t\"articleId\": 146,\n" +
                "\t\t\t\"sortId\": 3\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 11192,\n" +
                "\t\t\t\"uid\": 129176404,\n" +
                "\t\t\t\"articleId\": 140,\n" +
                "\t\t\t\"sortId\": 4\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 6887,\n" +
                "\t\t\t\"uid\": 139147812,\n" +
                "\t\t\t\"articleId\": 158,\n" +
                "\t\t\t\"sortId\": 5\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 24074,\n" +
                "\t\t\t\"uid\": 138126273,\n" +
                "\t\t\t\"articleId\": 224,\n" +
                "\t\t\t\"sortId\": 6\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 28128,\n" +
                "\t\t\t\"uid\": 128132074,\n" +
                "\t\t\t\"sortId\": 7\n" +
                "\t\t}, {\n" +
                "\t\t\t\"type\": 2,\n" +
                "\t\t\t\"bid\": 13816,\n" +
                "\t\t\t\"uid\": 126222849,\n" +
                "\t\t\t\"articleId\": 249,\n" +
                "\t\t\t\"sortId\": 8\n" +
                "\t\t}]\n" +
                "\t}]\n" +
                "}]";


        if (StringUtils.isNotBlank(conf)) {
            List<MaterialClassicHotSaleVO> lists = JSON.parseObject(conf, new TypeReference<List<MaterialClassicHotSaleVO>>() {
            });

            System.out.println(lists);
        }

    }

}
